.pc
.TH Editors.rakumod 1 2023-11-24
.SH "NAME"
GUI::Editors 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
v\&.0\&.1\&.0
.SH "TITLE"
GUI::Editors
.SH "SUBTITLE"
A module for managing the users GUI Editor preferences in a variety of programs\&.
.SH GUI::Editors

A module for managing the users GUI Editor preferences in a variety of programs\&. 
