.pc
.TH Editors.rakumod 1 2023-12-07
.SH GUI::Editors
.SS Table of Contents
.IP \(bu 2m
NAME [#name]
.IP \(bu 2m
AUTHOR [#author]
.IP \(bu 2m
VERSION [#version]
.IP \(bu 2m
TITLE [#title]
.IP \(bu 2m
SUBTITLE [#subtitle]
.IP \(bu 2m
COPYRIGHT [#copyright]
.IP \(bu 2m
Introduction [#introduction]
.SH "NAME"
GUI::Editors 
.SH "AUTHOR"
Francis Grizzly Smit (grizzly@smit\&.id\&.au)
.SH "VERSION"
0\&.1\&.0
.SH "TITLE"
GUI::Editors
.SH "SUBTITLE"
A Raku module for managing the users GUI Editor preferences in a variety of programs\&.
.SH Introduction

A Raku module for managing the users GUI Editor preferences in a variety of programs\&. 
